ver: 'tfb0_baseline'
model: 'CNN_Model'
dataset: 'base'
output_dir: 'models/'
data_path: '.open/'
gpu:
  mps: True
  use: True
  id: 0
train_params:
  seed: 42
  img_size: 224
  epochs: 10
  batch_size: 32
  val_batch_size: 64
  init_lr: 1e-3
  min_lr: 1e-6
  weight_decay: 0.0
  sch_cycle: 3
  folds: 5
  selected_folds: [0,1,2,3,4]
data:
  num_workers: 0
  num_classes: 2
